---
- name: Start a GCP instance which is currently stopped
  strategy: debug
  hosts: easytravel-tmp
  gather_facts: false

  tasks:

  - name: detroy instance
    gcp_compute_instance:
      state: absent
      name: "easytravel-tmp"
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
