---
- name: Start a GCP instance which is currently stopped
  hosts: 10.164.0.6
  gather_facts: false
  
  vars:
    auth_kind: serviceaccount
    ansible_user: easytravel
    ansible_password: easytravel

  tasks:

     - name: Start a GCP VM instance which is currently stopped
      gcp_compute_instance:
        name: "{{ name }}"
        deletion_protection: no
        machine_type: "{{ machineType }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: serviceaccount
        status: TERMINATED
      delegate_to: localhost
 
    - name: create a disk
      google.cloud.gcp_compute_disk:
        name: disk-instance
        size_gb: 20
        source_image: projects/tdpm-310914/global/images/training-image
        zone: "{{ zone }}"
        project: "{{ project }}"
        state: present
      delegate_to: localhost
      register: disk
    
    - name: create a network
      google.cloud.gcp_compute_network:
        name: network-instance
        auto_create_subnetworks: 'true'
        project: "{{ project }}"
        auth_kind: serviceaccount
        state: present
      delegate_to: localhost
      register: network    

    - name: create a address
      google.cloud.gcp_compute_address:
        name: address-instance
        region: europe-west4
        project: "{{ project }}"
        auth_kind: serviceaccount
        state: present
      delegate_to: localhost
      register: address
      
    - name: create a instance
      gcp_compute_instance:
          name: training-n
          machine_type: e2-medium
          disks:
          - auto_delete: 'true'
            boot: 'true'
            source: "{{ disk }}"
          network_interfaces:
          - network: "{{ network }}"
            access_configs:
            - name: External NAT
              nat_ip: "{{ address }}"
              type: ONE_TO_ONE_NAT
          zone: "{{ zone }}"
          project: "{{ project }}"
          auth_kind: serviceaccount
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      delegate_to: localhost
      
       - name: Run SSH command
      command: /usr/bin/pkill -f 'java'
      delegate_to: 34.91.229.240  
      
