---
- name: Start a GCP instance which is currently stopped
  hosts: easytravel-tmp
  gather_facts: false

  tasks:

    - name: Start a GCP VM instance which is currently stopped
      gcp_compute_instance:
        name: "{{ inventory_hostname_short }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: serviceaccount
        status: RUNNING
      delegate_to: localhost
