---
- name: Start a GCP instance which is currently stopped
  strategy: debug
  hosts: 10.164.0.6
  gather_facts: false

  tasks:

- name: create a instance
  gcp_compute_instance:
      - name: "{{ name }}"
        machine_type: "{{ machineType }}"
        disks:
        - auto_delete: true
          boot: true
          source: "{{ source }}"
        network_interfaces:
          - network: "default"
        zone: "{{ zone }}"
        project: "{{ project }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
