---
- name: Start a GCP instance which is currently stopped
  hosts: 10.164.0.6
  gather_facts: false
  
  vars:
    auth_kind: serviceaccount

  tasks:

    - name: Start a GCP VM instance which is currently stopped
      gcp_compute_instance:
        name: "{{ name }}"
        deletion_protection: no
        machine_type: "{{ machineType }}"
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: serviceaccount
        status: TERMINATED
      delegate_to: localhost
      
    - name: get info on an image
      gcp_compute_image_info:
        filters:
        - name = training
        project: "{{ project }}"
        auth_kind: serviceaccount
      
