---
- name: Start a GCP instance which is currently stopped
  strategy: debug
  hosts: easytravel-tmp
  gather_facts: false

  tasks:

    - name: Start a GCP VM instance which is currently stopped
      gcp_compute_instance:
        name: "{{ inventory_hostname_short }}"
        deletion_protection: no
        machine_type: "{{ machineType }}"
        disks:
        - autoDelete: true
          boot: true
          deviceName: easytravel-1
          diskSizeGb: '20'
          type: PERSISTENT
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: serviceaccount
        status: RUNNING
      delegate_to: localhost
