---
- name: Start a GCP instance which is currently stopped
  strategy: debug
  hosts: easytravel-tmp
  gather_facts: false

  tasks:

    - name: Start a GCP VM instance which is currently stopped
      gcp_compute_instance:
        name: "{{ inventory_hostname_short }}"
        deletion_protection: no
        machine_type: "{{ machineType }}"
        disks: "{{ disks }}"
        network_interfaces:
          - network: "default"
        zone: "{{ zone }}"
        project: "{{ project }}"
        auth_kind: serviceaccount
        status: RUNNING
      delegate_to: localhost
