---
- name: Start a GCP instance which is currently stopped
  strategy: debug
  hosts: 10.164.0.6
  gather_facts: false

  tasks:

  - name: detroy instance
    gcp_compute_instance:
      state: absent
      name: "{{ name }}"
      zone: "{{ zone }}"
      project: "{{ project }}"
